export enum Apps {
  main,
  shared,
  header,
  footer,
  vision360,
  personalData,
  records,
  sales,
  assetsProducts,
  channelsAndServices,
  historyInteractions,
  home,
  settingsView,
  scriptsView,
  kpis,
  outbounds,
  documentation,
}

export enum SharedModule {
  'react' = 'react',
  'react-dom' = 'react-dom',
  'react-router' = 'react-router',
  'react-helmet' = 'react-helmet',
  '@emotion/react' = '@emotion/react',
  '@emotion/styled' = '@emotion/styled',
  'zustand' = 'zustand',
  '@tanstack/react-query' = '@tanstack/react-query',
  '@hookform/resolvers' = '@hookform/resolvers',
  'react-hook-form' = 'react-hook-form',
  'zod' = 'zod',
}
